---
name: "jellyfin-plugin-template"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0"
jellyfin_version: "10.5.0"
nicename: "Template"
description: "Short description about your plugin"
overview: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Template.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.1"
